# @format

name: Validate PR is not leaking secrets

on:
  pull_request:
    types:
      - opened
      - ready_for_review

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  validate-pr-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Validate PR secrets
        uses: tomgrv/actions/check-secret@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          gitleaks-license: ${{ secrets.GITLEAKS_LICENSE }}
